# codec example yaml config

# signal related metrics
# -- sir: signal to interference ratio
# -- sar: signal to artifact ratio
# -- sdr: signal to distortion ratio
# -- ci-sdr: scale-invariant signal to distortion ratio
# -- si-snri: scale-invariant signal to noise ratio improvement
- name: signal_metric

# pesq related metrics
# -- pesq: perceptual evaluation of speech quality
- name: pesq

# stoi related metrics
# -- stoi: short-time objective intelligibility
- name: stoi


# pseudo subjective metrics
# -- utmos: UT-MOS score
# -- dnsmos: DNS-MOS score
# -- plcmos: PLC-MOS score
- name: pseudo_mos
  predictor_types: ["utmos", "dnsmos", "plcmos"]
  predictor_args:
    utmos:
      fs: 16000
    dnsmos:
      fs: 16000
    plcmos:
      fs: 16000

# speaker related metrics
# -- spk_similarity: speaker cosine similarity
#                    model tag can be any ESPnet-SPK huggingface repo at 
#                    https://huggingface.co/espnet
- name: speaker
  model_tag: default


